services:
  postgres-identity:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: identity_db
    volumes:
      - identity_db_data:/var/lib/postgresql/data
      # Mount the migration so it runs on startup
      - ../apps/identity-svc/migrations/000001_create_users_table.up.sql:/docker-entrypoint-initdb.d/01_create_users_table.sql
    networks:
      - scoutpulse-net

  postgres-football:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: football_db
    ports:
      - "5434:5432"
    volumes:
      - football_db_data:/var/lib/postgresql/data
      # Mount the migration so it runs on startup
      - ../apps/football-svc/migrations/000001_init_football_schema.up.sql:/docker-entrypoint-initdb.d/01_init_football_schema.sql
    networks:
      - scoutpulse-net

  identity-svc:
    build:
      context: ..
      dockerfile: apps/identity-svc/Dockerfile
    restart: on-failure
    environment:
      - DB_HOST=postgres-identity
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=identity_db
    depends_on:
      - postgres-identity
    ports:
      - "8080:8080"
    networks:
      - scoutpulse-net

networks:
  scoutpulse-net:
    driver: bridge

volumes:
  identity_db_data:
  football_db_data:
