// Command genkeys writes a JWT signing key pair as .env assignments.
//
// It exists because `make keys` shelled out to openssl, which is not present
// on a default Windows install -- and neither is make. The key material is
// identical; this just removes two tool dependencies from the one step every
// new checkout has to perform before the stack will start.
//
//	go run ./cmd/genkeys >> ../../.env
package main

import (
	"fmt"
	"os"
	"strings"

	"github.com/scoutpulse/libs/auth"
)

func main() {
	privatePEM, publicPEM, err := auth.GenerateKeyPair(auth.MinRSAKeyBits)
	if err != nil {
		fmt.Fprintf(os.Stderr, "generating key pair: %v\n", err)
		os.Exit(1)
	}

	// Newlines are escaped so each key is a single .env line. Both the compose
	// file and the services read them back through the environment, where a
	// literal \n in a quoted value is the conventional encoding.
	fmt.Println()
	fmt.Println("# Generated by 'go run ./cmd/genkeys'. Never commit these.")
	fmt.Printf("JWT_PRIVATE_KEY=\"%s\"\n", escapeNewlines(privatePEM))
	fmt.Printf("JWT_PUBLIC_KEY=\"%s\"\n", escapeNewlines(publicPEM))
}

func escapeNewlines(pem []byte) string {
	return strings.ReplaceAll(strings.TrimRight(string(pem), "\n"), "\n", `\n`)
}
